#!/bin/bash 

# A script that will print out a message from a variable

hello_message='Hello, YouTube!' 
current_dir=$(pwd) 
variable_wont_change="blue"

echo $hello_message from $current_dir your favorite color is $variable_wont_change